# action.yml
name: 'Dependabot terraform multiplatform hashes'
description: 'Automatically update dependabot terraform pull requests to include multiplatform hashes.'
runs:
  using: 'docker'
  image: 'Dockerfile'
